/// <reference types="expo/types" />

// Normally auto-generated by `expo start` and gitignored, but CI never runs
// that, so this is committed deliberately (see apps/mobile/.gitignore).
// Regenerate via `expo start` if the Expo SDK major version changes.
